version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-api
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
    ports:
      - '8006:80'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local
    restart: "no"
  db:
    image: postgres
    restart: always
    container_name: auth-db
    user: postgres
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    volumes:
      - postgres:/data/postgres
    ports:
      - "5436:5432"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - local

volumes:
  postgres:

networks:
  local:
    driver: bridge
